spring.application.name=account-service
server.port=8081

jwt.secret=r1d3l1nk-4cc0unt-s3rv1c3-jwt-s1gn1ng-k3y-ch4ng3-m3-1n-pr0duct10n-2026
jwt.expiration-ms=3600000

spring.data.mongodb.uri=mongodb://localhost:27017/ridelink_account
